# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_engine_wrappers", use_symbols = TRUE, package_name = "engine")

#' @docType package
#' @usage NULL
#' @useDynLib engine, .registration = TRUE
NULL

gnu_parallel_run_pipeline <- function(pipeline) .Call(wrap__gnu_parallel_run_pipeline, pipeline)


# nolint end
