# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pipelinr_wrappers", use_symbols = TRUE, package_name = "pipelinr")

#' @docType package
#' @usage NULL
#' @useDynLib pipelinr, .registration = TRUE
NULL

gnu_parallel_run_task_group <- function(task_group, ssh_login_file) .Call(wrap__gnu_parallel_run_task_group, task_group, ssh_login_file)


# nolint end
